services:
  kvstore_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: personal-kv-store-server:latest
    ports:
      - "50051:50051"
    networks:
      - kvstore_net
    volumes:
      - kvstore_data:/data
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 3

  kvstore_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: personal-kv-store-client:latest
    depends_on:
      - kvstore_server
    networks:
      - kvstore_net
    stdin_open: true

  test:
    build:
      context: .
      dockerfile: ./tests/Dockerfile.test
    image: personal-kv-store-test:latest
    container_name: kvstore_test
    depends_on:
      - kvstore_server
    networks:
      - kvstore_net
    environment:
      - KVSTORE_SERVER_ADDR=kvstore_server:50051
    command: ["go", "test", "./tests"]

networks:
  kvstore_net:
    driver: bridge

volumes:
  kvstore_data: