services:
  kvserver:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: personal-kv-store-server:latest
    container_name: kvstore_server
    ports:
      - "50051:50051"
    networks:
      - kvnet
    volumes:
      - kvstore_data:/data
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50051"]
      interval: 30s
      timeout: 10s
      retries: 3

  kvstore_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: personal-kv-store-client:latest
    container_name: kvstore_client
    depends_on:
      - kvserver
    networks:
      - kvnet
    stdin_open: true

networks:
  kvnet:
    driver: bridge

volumes:
  kvstore_data: