name: CI-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build images and start services
        run: |
          docker compose up --build -d kvstore_server
          # Optionally, wait a few seconds to ensure the server is ready
          sleep 5

      - name: Run tests
        run: docker compose run --rm test

      - name: Tear down
        run: docker compose down